kit-clj/kit

- libs/lein-template/resources/leiningen/new/kit/deps.edn
Add nrepl.cmdline to :dev alias.
When starting application with `clj -M:dev` interactive repl session will be started, as well as `nrepl-server` on random free port.
The implementation outsource to `nrepl.cmdline` utility function of nrepl.
Fully functional repl could be implemented in the future using `reply` library, the same that is used by `lein repl` and `boot repl`, but I had some issues with it when trying to use it.
> Add nrepl-server to :dev alias

- libs/lein-template/resources/leiningen/new/kit/README.md
Minor clarifications to the README as I mentioned in #15
For Cursive, I was not able to select an alias from deps myself so I'm not 100% sure this instruction is correct (there was no dropdown, or anything). I'm not a Cursive user but I still managed to create a manual configuration by choosing clojure.main as my REPL and selecting "Run with IntelliJ project classpath" as instructed.
> Clarifying template README

- libs/lein-template/resources/leiningen/new/kit/env/dev/clj/user.clj
Missing watch-deps namespace in user.clj causing error: `No such namespace: watch-deps` when trying to enable hot loading for deps
> Add watch-deps ns to :require

- libs/lein-template/resources/leiningen/new/kit/resources/system.edn
Related to this change https://github.com/kit-clj/kit/pull/41
The `:cookie-name` should not be inside `:cookie-attrs` based on the [ring.middleware.session/wrap-session](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/session.clj#L94-L99)
> fix session map cookie-name

- libs/kit-xtdb/deps.edn
- libs/lein-template/resources/leiningen/new/kit/resources/system.edn
Uses the latest XTDB version (v1.21.0-beta3) which is using a version of RockDB that also works on Mac M1 computers.
> Adds a default configuration for XTDB

- libs/kit-generator/src/kit/generator/modules.clj
help message when no modules are present
Why:
The original message may cause unecessery confusion for new developers.
Example:
```
user> (kit/list-modules)
No modules installed, maybe run `sync-modules`
:done
user> (sync-modules)
Syntax error compiling at (*cider-repl clojure/foo:localhost:45381(clj)*:11685:7).
user> sync-modules
Syntax error compiling at (*cider-repl clojure/foo:localhost:45381(clj)*:0:0).
user> (kit/sync-modules)
:done
```
> Add full command name `kit/sync-modules to list-modules

- libs/lein-template/resources/leiningen/new/kit/gitignore
I'm not sure about this one, but the `modules/` dir doesn't seem like something to track in a kit project's git repo. Especially since `modules/kit-modules` is a git repo checkout.
> git ignore downloaded kit modules

- libs/lein-template/resources/leiningen/new/kit/env/dev/clj/env.clj
- libs/lein-template/resources/leiningen/new/kit/env/prod/clj/env.clj
- libs/lein-template/resources/leiningen/new/kit/src/clj/web/middleware/core.clj
[`<<ns-name>>.core`](https://github.com/kit-clj/kit/blob/master/libs/lein-template/resources/leiningen/new/kit/src/clj/core.clj#L46) uses `:start`.
(And snuck in a minor whitespace fix.)
> Fixed :start keys in env defaults

- bb.edn
- build.clj
- build/kit/sync_lib_deps.clj
- deps.edn
- justfile
- sync-lib-deps.clj
- Update `sync-lib-deps` so it can be used from `build.clj`
- Use `versions.edn` for the `deps-template` version within `lein-template`
- Allow syncing of one lib at a time for `build.clj` usage
- Update outdated deps in `bb.edn`
- Run `sync-lib-deps` when attempting to install a lib and print an error when changes need to be committed
> Sync lib deps during publishing

- bb.edn
- build.clj
- build/deps.edn
- build/kit/sync_lib_deps.clj
Right now the `build.clj` script does run `sync-lib-deps`, but it only causes the build to fail the first time it runs.
This PR updates the `build.clj` script to check for changes in Git before building. If there are uncommitted changes, you'll get an error message:
```
$ bb publish-all-local
+ clojure -T:build all :publish false
Syncing lib deps...
libs/kit-core/deps.edn
Execution error (ExceptionInfo) at build/assert-clean-working-directory (build.clj:49).
All changes must be committed before building.
Full report at:
/var/folders/tt/73f6l1j971n03fsxstmz_g280000gn/T/clojure-3948577615227481739.edn
Error while executing task: publish-all-local
```
I figure this is better than trying to commit changes automatically. This check isn't specific to `sync-lib-deps` so it will also work if …
> Improvements to `sync-lib-deps` integration in `build.clj`

- libs/deps-template/resources/io/github/kit_clj/kit/.dir-locals.el
This change should allow emacs users to jack in from an out-of-the-box kit template.
> Add dir-locals for CIDER integration

- libs/deps-template/resources/io/github/kit_clj/kit/.dir-locals.el
Previous commit was incorrect anyway, since it was supposed to be a list of lists. Scoping explicitly to clojure-mode also works around bugs in doom emacs / envrc hook priority, where dir-locals are immediately loaded, and then clobbered into nothingness when the envrc major mode loads. Setting the major-mode scope for these variables works around the issue as envrc is explicitly hooked in before other major-modes load, effectively deferring dir-locals until after the direnv loads and thus having the correct additive effect.
> Scope dir-locals vars to clojure-mode only

- libs/deps-template/resources/io/github/kit_clj/kit/env/dev/clj/env.clj
- libs/deps-template/resources/io/github/kit_clj/kit/env/prod/clj/env.clj
On a new project, I got the following in `<<ns-name>>.env`:
```(def defaults
{:init       (fn []
(log/info "\n-=[ starting]=-"))
:start      (fn []
(log/info "\n-=[ started successfully]=-"))
:stop       (fn []
(log/info "\n-=[ has shut down successfully]=-"))
:middleware (fn [handler _] handler)
:opts       {:profile :prod}})
```
Looks like the templating is not quite right. Replaced with <<ns-name>>, let me know if this isn't intended.
> <<app>> appears unused, replace with <<ns-name>>

- libs/deps-template/resources/io/github/kit_clj/kit/src/clj/web/routes/api.clj
This change removes Integrant `opts` from `route-data` since `opts` are already accessible directly in `api-routes`.
TODO: update documentation and sample projects to match this change.
> refactored resource access in routes

- libs/deps-template/resources/io/github/kit_clj/kit/deps.edn
Per nvd-clojure:
```
+-------------------------------+--------------------------------+
| dependency                    | status                         |
+-------------------------------+--------------------------------+
| commons-fileupload-1.4.jar    | CVE-2023-24998                 |
| jackson-databind-2.13.2.2.jar | CVE-2022-42004, CVE-2022-42003 |
+-------------------------------+--------------------------------+
```
Cheers - V
> Address CVEs in deps.edn template

- libs/deps-template/resources/io/github/kit_clj/kit/deps.edn
This can help other tooling (which can read deps.edn) know the url.
Cheers - V
> Add explicit test-runner `:git/url`

- libs/deps-template/resources/io/github/kit_clj/kit/test/clj/test_utils.clj
I noticed that the system-fixture was missing a teardown step for testing.
I added a few high level API tests for my hobby project with mock.ring.request and used `utils/system-fixture` and `utils/system-state` from the `test_utils.clj` to configure my database and handler. The tests passed, but I noticed that when I ran `clj -X:test` from the CLI the process would hang, or if ran the `(run-tests)` function in the repl mutiple times I would get a "bind address already in use" error.
I figure the fixture starts up the whole integrant system including the http-server, which doesn't exit. In any case, adding this teardown step worked locally for me, and seems to align with the practices listed on the [use-fixtures documentation](https://clojuredocs.org/clojure.test/use-fixtures).
I don't …
> adds teardown step for test system-fixture

- libs/kit-nrepl/deps.edn
- libs/kit-nrepl/src/kit/edge/utils/nrepl.clj
fixes https://github.com/kit-clj/kit/issues/91
Mostly inspired by how this is done in other components, tested it in the REPL with `integrant.repl/reset` with something like this:
```clj
(require '[integrant.repl :as igr])
(igr/set-prep! #(ig/prep {:nrepl/server {:port 4004}}))
(igr/reset)
```
--- 
I also added another commit (happy to open a separate PR or remove it) but just wanted to check in about the idea: I usually start my development system via something like `bb dev` this will launch an nREPL server that I then connect to. I think with kit it could make sense to do something similar and only inject that component in development?
> Make nREPL server persist over resets

- libs/kit-core/src/kit/ig_utils.clj
- libs/kit-sql-conman/src/kit/edge/db/sql/conman.clj
Perhaps this is overkill, but since a lot of your components will probably depend on the :db.sql/query-fn component the fact that it was not resumable caused pretty much all components to be reloaded when doing `(reset)`.
This PR adds an explicit check if any of the hugsql queries files are modified, and if not the old implementation is returned upon resume.
Requires Java 7+ since java.nio.file APIs are used for getting the modification time. (java.io.File#lastModified unfortunately always seem to return 0, at least on macOS).
> Refrain from re-initializing query-fn if queries files not modified

- libs/deps-template/resources/io/github/kit_clj/kit/env/dev/clj/user.clj
This is a consequence of ce18f13c772d30015ccaac79dd35f833c124356c
> Properly resolve query-fn

- .gitignore
- libs/deps-template/resources/io/github/kit_clj/kit/gitignore
- libs/deps-template/resources/io/github/kit_clj/kit/resources/system.edn
- libs/deps-template/resources/io/github/kit_clj/kit/src/clj/web/handler.clj
- libs/deps-template/resources/io/github/kit_clj/kit/src/clj/web/routes/api.clj
Fixes #48 by implementing reloading of routes as recommended by `reitit` in https://github.com/metosin/reitit/blob/master/doc/advanced/dev_workflow.md 
To take advantage of reloading, one has to return a function instead of a vector in his route definition. Check `(defmethod ig/init-key :reitit.routes/api` as an example.
The solution is backward compatible: it still accepts vectors as a route definition, but in that case no reloading.
The reloading is by default enabled only in `:dev` profile.
@yogthos , @nikolap please review before merging. I did some testing, but I'm not sure if there is a better/cleaner way to hook it up in integrant.
> Implement reitit reloading

- libs/deps-template/resources/io/github/kit_clj/kit/src/clj/web/handler.clj
Because the body is not HTML, so it shouldn't be `text/html`.
> Fix content-type of error responses to text/plain

- libs/kit-sql-conman/src/kit/edge/db/sql/conman.clj
@yogthos 
A few months ago you kindly accepted my PR to allow multiple hugsql scripts in system.edn.  The previous code inspects file edit time and if it has updated reloads conman.  Now that we have multiple files we have to map over all the file edit times but of course map is lazy.  As a result the previous edit times would get evaluated at the same time as the current one and never show any difference (!).  Very easy fix!
Matt
> Bugfix on Conman

- build/deps.edn
- build/kit/sync_lib_deps.clj
- libs/deps-template/resources/io/github/kit_clj/kit/env/dev/clj/user.clj
- libs/deps-template/resources/io/github/kit_clj/kit/src/clj/core.clj
- libs/kit-core/deps.edn
- libs/kit-generator/test/resources/core.clj
- libs/kit-hato/deps.edn
- libs/kit-http-kit/deps.edn
- libs/kit-http-kit/src/kit/edge/server/http_kit.clj
- libs/kit-nrepl/deps.edn
- libs/kit-quartz/deps.edn
- libs/kit-redis/deps.edn
- libs/kit-repl/deps.edn
- libs/kit-repl/src/kit/edge/utils/repl.clj
- libs/kit-selmer/deps.edn
- libs/kit-sql-conman/deps.edn
- libs/kit-sql-hikari/deps.edn
- libs/kit-sql-migratus/deps.edn
- libs/kit-undertow/deps.edn
- libs/kit-undertow/src/kit/edge/server/undertow.clj
- libs/kit-xtdb/deps.edn
This PR addresses https://github.com/kit-clj/kit/issues/138 by upgrading `integrant` library to `0.9.0` version both in core and kit-modules. 
It also replaces `ig/prep-key` with `ig/expand-key` as suggested in [integrant's README](https://github.com/weavejester/integrant/tree/master?tab=readme-ov-file#replacing-prep).
Subsequent changes on that matter may include documentation:
- https://kit-clj.github.io/docs/integrant.html
- https://kit-clj.github.io/docs/servers.html
> Upgrade integrant to 0.9.0 version and use `expand` instead of `prep`

- libs/deps-template/resources/io/github/kit_clj/kit/deps.edn
- libs/kit-generator/src/kit/generator/modules/generator.clj
trim whitespace specifically from 2 files:
- libs/deps-template/resources/io/github/kit_clj/kit/deps.edn
- libs/kit-generator/src/kit/generator/modules/generator.clj
Note:
- it looks like more can probably be done for `libs/deps-template/resources/io/github/kit_clj/kit/deps.edn` to tidy things up a bit, but I am just choosing to tackle the whitespace-only line first to make for a better dev experience (when I open up `deps.edn` in my editor, this line is highlighted and makes me wonder; and I don't think this is unique to my editor (am using Emacs Prelude atm))
- I an choosing to ignore the trailing whitespace in CHANGELOG.md (but feel free to let me know if you want those to be removed as well so I can include it in this PR)
> cosmetic: trim whitespace in code files

- libs/deps-template/resources/io/github/kit_clj/kit/deps.edn
- libs/deps-template/resources/io/github/kit_clj/kit/test/clj/test_utils.clj
- libs/deps-template/resources/io/github/kit_clj/kit/test/clj/web/request_test.clj
This is a helping hand to get started with testing the ring app with mock requests. It should be especially helpful for beginners, as it isn't readily apparent how to do this. I figure since there is a handler in the template we might as well have a test for it. 
question: Should this be copied into the lein-template, or is there a way to avoid that?
question: Should byte-streams be added to the main dependencies? (I tend to add it all the time)
What do you think of this idea? 
Thanks!
> add a working request test to template

- libs/deps-template/resources/io/github/kit_clj/kit/env/dev/clj/env.clj
This pull requests is simply a removal of outdated artifact from previous versions that adds `:persist-data? true` to the application defaults.
Addressing issue: https://github.com/kit-clj/kit/issues/157
> remove `:persist-data? true` option from `env.clj` app defaults

- libs/kit-generator/src/kit/api.clj
- libs/kit-generator/src/kit/generator/modules/dependencies.clj
- libs/kit-generator/test/kit/generator/modules/dependencies_test.clj
Hi
I was trying `kit` and I run into this issue.
```bash
❯ clojure -Tclj-new create :template io.github.kit-clj :name luca/guestbook
Generating kit project.
❯ cd guestbook
❯ clj -M:dev
Clojure 1.12.0
user=> (kit/sync-modules)
:done
user=> (kit/install-module :kit/cljs)
:kit/cljs requires following modules: nil
applying features to config: [:base :reagent]
failed to read asset in project: resources/html/home.html
error: resources/html/home.html (No such file or directory)
updating file: resources/html/home.html
failed to install module :kit/cljs
java.lang.IllegalArgumentException: No method in multimethod 'get-resource' for dispatch value: null
at clojure.lang.MultiFn.getFn(MultiFn.java:156)
at clojure.lang.MultiFn.invoke(MultiFn.java:233)
at …
```
> fix: resolve dependencies and install modules
